import 'dotenv/config'

const DEPLOYMENT_ENV = process.env.DEPLOYMENT_ENV || (process.env.BUILD_MODE === 'production' ? 'production' : 'development')
const API_V2_REQUESTED = process.env.ENABLE_API_V2 === 'true'

export const env = {
  MONGODB_URI: process.env.BUILD_MODE == 'production' ? process.env.MONGODB_URI_PRODUCTION : process.env.MONGODB_URI_DEVELOPMENT,
  DATABASE_NAME: process.env.DATABASE_NAME,
  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,

  BUILD_MODE: process.env.BUILD_MODE,
  DEPLOYMENT_ENV,
  ENABLE_API_V2: API_V2_REQUESTED && DEPLOYMENT_ENV !== 'production',
  ACTIVE_FINANCIAL_WRITE_VERSION: process.env.ACTIVE_FINANCIAL_WRITE_VERSION || 'V1',
  V2_FEATURE_FLAGS_JSON: process.env.V2_FEATURE_FLAGS_JSON || '',

  POSTGRESQL_DATABASE_URL: process.env.POSTGRESQL_DATABASE_URL,
  POSTGRESQL_DIRECT_URL: process.env.POSTGRESQL_DIRECT_URL,

  AGENDA_MONGODB_URI: process.env.AGENDA_MONGODB_URI,
  AGENDA_DATABASE_NAME: process.env.AGENDA_DATABASE_NAME,

  V2_REDIS_NAMESPACE: process.env.V2_REDIS_NAMESPACE,
  V2_EMAIL_MODE: process.env.V2_EMAIL_MODE || 'disabled',
  V2_SOCKET_MODE: process.env.V2_SOCKET_MODE || 'disabled',
  V2_NOTIFICATION_MODE: process.env.V2_NOTIFICATION_MODE || 'disabled',

  AUTHOR: process.env.AUTHOR,

  WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,

  BREVO_API_KEY: process.env.BREVO_API_KEY,
  ADMIN_EMAIL_ADDRESS: process.env.ADMIN_EMAIL_ADDRESS,
  ADMIN_EMAIL_NAME: process.env.ADMIN_EMAIL_NAME,

  ACCESS_TOKEN_SECRET_SIGNATURE: process.env.ACCESS_TOKEN_SECRET_SIGNATURE,
  ACCESS_TOKEN_LIFE: process.env.ACCESS_TOKEN_LIFE,

  REFRESH_TOKEN_SECRET_SIGNATURE: process.env.REFRESH_TOKEN_SECRET_SIGNATURE,
  REFRESH_TOKEN_LIFE: process.env.REFRESH_TOKEN_LIFE,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  // Redis
  REDIS_URL: process.env.REDIS_URL,
  CACHE_ENABLED: process.env.CACHE_ENABLED === 'true',
  CACHE_DEFAULT_TTL: process.env.CACHE_DEFAULT_TTL ? parseInt(process.env.CACHE_DEFAULT_TTL) : 3600,

  // Per - resource TTLs
  CACHE_TTL_BANKS: process.env.CACHE_TTL_BANKS ? parseInt(process.env.CACHE_TTL_BANKS) : 86400,
  CACHE_TTL_CATEGORIES: process.env.CACHE_TTL_CATEGORIES ? parseInt(process.env.CACHE_TTL_CATEGORIES) : 3600,
  CACHE_TTL_ACCOUNTS: process.env.CACHE_TTL_ACCOUNTS ? parseInt(process.env.CACHE_TTL_ACCOUNTS) : 3600
}
